version: '1.0'

services:
  db:
    image: mysql
    restart: always
    environment:
#      MYSQL_DATABASE: ${MYSQL_DB_NAME}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: WatchWaveDB
      MYSQL_USER: ThirdImpact
      MYSQL_PASSWORD: ThirdImpact123!
      MYSQL_ROOT_PASSWORD: ThirdImpact123!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - watchwave_networks

  backend:
    build: ./backend
    container_name: spring
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db/WatchWaveDB?characterEncoding=UTF-8"
      MYSQL_USER: ThirdImpact
      MYSQL_PASSWORD: ThirdImpact123!
#      SPRING_DATASOURCE_URL: "jdbc:mysql://db/backend?characterEncoding=UTF-8"
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 1234
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - watchwave_networks

volumes:
  mysql_data:

networks:
  watchwave_networks: