#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/WatchWaveDB?characterEncoding=UTF-8
#    username: ThirdImpact123
#    password: ThirdImpact123!
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ahwhew?characterEncoding=UTF-8
#    username: root
#    password: 1234
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql-container:3306/watchwave
#    username: root
#    password: 1234